language: bash
services: docker

env:
  global:
    - IMAGE_NAME=steamcmd

before_script:
  - REPOSITORY="${REGISTRY_NAMESPACE}/${IMAGE_NAME}"

  - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

script:
  - date
  - docker pull "${REPOSITORY}:${VARIANT}" || true
  - docker build
    --cache-from "${REPOSITORY}:${VARIANT}"
    -t "${REPOSITORY}:${VARIANT}"
    "${VARIANT}/"
  - if [ "$LATEST" = true ]; then
      docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:latest";
    fi
  - docker images

  # Test the image
  - if [ "${NO_TEST_RUN}" != true ]; then
      docker run -t --rm "${REPOSITORY}:${VARIANT}" /bin/bash -c "printenv && ls -al && exec steamcmd.sh +login anonymous +quit";
    fi

  - if [ "${NO_PUSH}" != true ]; then
      docker push "${REPOSITORY}";
    fi

after_script:
  - docker logout