trigger:
  branches:
    include:
    - '*'
  tags:
    exclude:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Ubuntu-Git:
        VARIANT: git
        LATEST: true
      Ubuntu-Minimal:
        VARIANT: minimal
  variables:
    IMAGE_NAME: steamcmd
    BASE_IMAGE: ubuntu:xenial-20181005
  timeoutInMinutes: 20
  steps:
  - script: |
      hostname
      whoami
      cat /etc/*release
      lscpu
      free
      df -h
      pwd
      docker info
      docker version
    displayName: Display system info
  - script: |
      REPOSITORY="${REGISTRY_NAMESPACE}/${IMAGE_NAME}"
      BUILD_TAG=$( echo "${BUILD_SOURCEBRANCH}" | sed -rn 's/^refs\/heads\/build\/(.*)/\1/p' )

      echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin

      # Set job-scoped variables
      echo "##vso[task.setvariable variable=REPOSITORY]${REPOSITORY}"
      echo "##vso[task.setvariable variable=BUILD_TAG]${BUILD_TAG}"
    env:
      REGISTRY_PASSWORD: $(REGISTRY_PASSWORD)
    displayName: Before script
  - script: |
      set -e
      date
      # Build the steamcmd image
      time docker pull "${REPOSITORY}:${VARIANT}" || true
      time docker build \
          --cache-from "${REPOSITORY}:${VARIANT}" \
          --build-arg BASE_IMAGE="${BASE_IMAGE}" \
          -t "${REPOSITORY}:${VARIANT}" \
          --label "game_distributor=steamcmd" \
          "${VARIANT}/"
      if [ "${LATEST}" = 'true' ]; then
          docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:latest"
      fi
      if [ -n "${BUILD_TAG}" ]; then
          docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${VARIANT}-${BUILD_TAG}"
      fi
      docker images
      docker inspect "${REPOSITORY}:${VARIANT}"
      docker history "${REPOSITORY}:${VARIANT}"
    displayName: Build image
  - script: |
      set -e
      # Test the image
      docker run -t --rm "${REPOSITORY}:${VARIANT}" /bin/bash -c "printenv && echo && ls -al && echo && exec steamcmd.sh +login anonymous +quit"
    displayName: Test image
  - script: |
      set -e
      # Push the image
      if [ -n "${BUILD_TAG}" ]; then
          time docker push "${REPOSITORY}"
      fi
    displayName: Push image
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/build/'))
  - script: |
      docker logout
    displayName: After script
    condition: always()
